### ISSUE TITLE
Linking with dockerhub

### ISSUE THREAD

**Issue by Mailblocker** [JakeWharton/docker-mbsync#7]
Hi,
do you consider to link the github repo with the docker hub repo?

This would increase the integrity of the project. I know you're using github actions and therefore do not need the auto build of dockerhub. But as far as I know you can link the two anyways and still just use the github actions just as it is.

**Comment by JakeWharton** [comment]
This is blocked by https://github.com/docker/roadmap/issues/115. Even if you link your GItHub account, you have to be using autobuilds for the description and readme to update.

I'll try to find time to copy over the READMEs of all my Docker projects today, to at least ensure they're not all blank.

**Comment by Mailblocker** [comment]
Hm okay, I thought it would be possible to link them without any other further usage.
