### ISSUE TITLE
Update mbsync to 1.4.3

### ISSUE THREAD

**Issue by jgod** [JakeWharton/docker-mbsync#9]
The current version (1.3.3) doesn't have 'UserCmd':
```bash
/config/mbsync.rc:7: unknown/misplaced keyword 'UserCmd'
```

https://sourceforge.net/p/isync/isync/ci/03b15dbdd341375e2f3350bdfe0d957b64c4edde/

**Comment by JakeWharton** [comment]
Thanks for the heads up. I will try to put out a new version very soon!

**Comment by JakeWharton** [comment]
Released as 1.3.0.
